<?php

namespace AppBundle\Repository;

/**
 * SAdvertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SAdvertisementRepository extends \Doctrine\ORM\EntityRepository
{
}
