<?php

namespace AppBundle\Repository;

/**
 * SEstateAgentPhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SEstateAgentPhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
